name: whole
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  csc_picker: ^0.2.6
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.0.0+2
  percent_indicator: ^4.0.0
  vertical_picker: ^0.0.1
  numberpicker: ^2.1.1
  flutter_picker: ^2.0.3
  charts_flutter: ^0.12.0
  grouped_list: ^4.2.0
  dropdown_button2: ^1.4.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Whole_icons
      fonts:
        - asset: assets/icons/Whole_icons.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
